image: gradle:7.0.2

pipelines:
  default:
    - parallel:
      - step:
          name: Build and Test
          caches:
            - gradle
          script:
            - gradle asciidoctorRevealJs
